### ISSUE TITLE
Issues templates don't appear when creating a issue.

### ISSUE THREAD

**Issue by darthzyklus** [freecodecamp-venezuela/ecommerce-coffee#7]
When a user wants to create an issue on this project the issues templates don't appear as an option

1. Go to  the issue section
2. Click on new issue
3. Check it out if the issues templates are available

**Expected behavior**
The issues templates should show as option to improve the issue creation process

**Comment by Hmerin** [comment]
@darthzyklus Take into a count that the changes related to templates must be merged on master in order to apear on github.

**Comment by darthzyklus** [comment]
closed by #8
